# Generated by Django 3.0.6 on 2020-06-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_auto_20200623_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='boast',
            field=models.BooleanField(default=True),
        ),
    ]
