# Generated by Django 3.0.6 on 2020-06-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0005_auto_20200623_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='roast',
        ),
    ]
