# Generated by Django 3.0.6 on 2020-06-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0006_remove_post_roast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='private_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='public_url',
        ),
    ]
